[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "http://sbtaxpros.net/*"
  to = "https://sbtaxpros.net/:splat"
  status = 301
  force = true
