[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "http://sbtaxpros.net/*"
  to = "https://sbtaxpros.net/:splat"
  status = 301
  force = true

# Pretty URLs for the new pages
[[redirects]]
  from = "/book"
  to   = "/book/"
  status = 200
  force = true

[[redirects]]
  from = "/thank-you"
  to   = "/thank-you/"
  status = 200
  force = true
